description: |
  Use one of our pre-included templates for sending a success notification when a tagged deployment passes.
  Enter a Target ID in the target parameter to specify which Glue group or thread to ping.
  Ensure the "glue/notify" command is the last command in a job to accurately capture the status.
usage:
  version: 2.1
  orbs:
    glue: gluegroups/glue@1.0
    node: circleci/node@4.1
  jobs:
    deploy:
      executor:
        name: node/default
      steps:
        - checkout
        - node/install-packages
        - run:
            command: npm run deploy
        - glue/notify:
            event: pass
            template: success_tagged_deploy_1
            target: grp_ABCXYZ
  workflows:
    deploy_and_notify:
      jobs:
        - deploy:
            context:
              - glue-secrets